// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskTracker.Data;

#nullable disable

namespace TaskTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260420135224_AddIndexes")]
    partial class AddIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskTracker.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Changes")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Changes")
                        .HasDatabaseName("IX_AuditLogs_Changes_GIN");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Changes"), "gin");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.HasIndex("NewValues")
                        .HasDatabaseName("IX_AuditLogs_NewValues_GIN");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NewValues"), "gin");

                    b.HasIndex("OldValues")
                        .HasDatabaseName("IX_AuditLogs_OldValues_GIN");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OldValues"), "gin");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserName");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("Timestamp", "Action");

                    b.HasIndex("Timestamp", "EntityType");

                    b.HasIndex("UserName", "Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HiddenTasksJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("HiddenTasksJson");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("HiddenTasksJson")
                        .HasDatabaseName("IX_Branches_HiddenTasksJson_GIN");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HiddenTasksJson"), "gin");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("IsActive", "DepartmentId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ambassador Branch, Hargeisa, Somaliland",
                            Code = "AMB-001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "ambassador@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Ambassador",
                            Notes = "",
                            Phone = "+252 63 000001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Arabsiyo Branch, Hargeisa, Somaliland",
                            Code = "ARB-002",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "arabsiyo@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Arabsiyo",
                            Notes = "",
                            Phone = "+252 63 000002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Aw-Aden Branch, Hargeisa, Somaliland",
                            Code = "AWA-003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "awaden@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Aw-Aden",
                            Notes = "",
                            Phone = "+252 63 000003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Buurta-kala-jeexan Branch, Hargeisa, Somaliland",
                            Code = "BKT-004",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "buurtakalajeexan@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Buurta-kala-jeexan",
                            Notes = "",
                            Phone = "+252 63 000004"
                        },
                        new
                        {
                            Id = 5,
                            Address = "DLD Branch, Hargeisa, Somaliland",
                            Code = "DLD-005",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "dld@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "DLD",
                            Notes = "",
                            Phone = "+252 63 000005"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Dunbuluq Branch, Hargeisa, Somaliland",
                            Code = "DUN-006",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "dunbuluq@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Dunbuluq",
                            Notes = "",
                            Phone = "+252 63 000006"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Faarah-Nour Branch, Hargeisa, Somaliland",
                            Code = "FAN-007",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "faarahnour@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Faarah-Nour",
                            Notes = "",
                            Phone = "+252 63 000007"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Faluuja Branch, Hargeisa, Somaliland",
                            Code = "FAL-008",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "faluuja@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Faluuja",
                            Notes = "",
                            Phone = "+252 63 000008"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Gabiley Branch, Hargeisa, Somaliland",
                            Code = "GAB-009",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "gabiley@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Gabiley",
                            Notes = "",
                            Phone = "+252 63 000009"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Ganad Branch, Hargeisa, Somaliland",
                            Code = "GAN-010",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "ganad@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Ganad",
                            Notes = "",
                            Phone = "+252 63 000010"
                        },
                        new
                        {
                            Id = 11,
                            Address = "GNT Branch, Hargeisa, Somaliland",
                            Code = "GNT-011",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "gnt@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "GNT",
                            Notes = "",
                            Phone = "+252 63 000011"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Haaruun Branch, Hargeisa, Somaliland",
                            Code = "HAA-012",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "haaruun@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Haaruun",
                            Notes = "",
                            Phone = "+252 63 000012"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Iftin Branch, Hargeisa, Somaliland",
                            Code = "IFT-013",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "iftin@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Iftin",
                            Notes = "",
                            Phone = "+252 63 000013"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Isha-borama Branch, Hargeisa, Somaliland",
                            Code = "ISB-014",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "ishaborama@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Isha-borama",
                            Notes = "",
                            Phone = "+252 63 000014"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Jig Branch, Hargeisa, Somaliland",
                            Code = "JIG-015",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "jig@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Jig",
                            Notes = "",
                            Phone = "+252 63 000015"
                        },
                        new
                        {
                            Id = 16,
                            Address = "June Branch, Hargeisa, Somaliland",
                            Code = "JUN-016",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "june@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "June",
                            Notes = "",
                            Phone = "+252 63 000016"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Kililka Branch, Hargeisa, Somaliland",
                            Code = "KIL-017",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "kililka@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Kililka",
                            Notes = "",
                            Phone = "+252 63 000017"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Laanta-Hawada Branch, Hargeisa, Somaliland",
                            Code = "LAH-018",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "laantahawada@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Laanta-Hawada",
                            Notes = "",
                            Phone = "+252 63 000018"
                        },
                        new
                        {
                            Id = 19,
                            Address = "M.mooge Branch, Hargeisa, Somaliland",
                            Code = "MMO-019",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "m.mooge@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "M.mooge",
                            Notes = "",
                            Phone = "+252 63 000019"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Masala Branch, Hargeisa, Somaliland",
                            Code = "MAS-020",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "masala@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Masala",
                            Notes = "",
                            Phone = "+252 63 000020"
                        },
                        new
                        {
                            Id = 21,
                            Address = "New-Hargeisa Branch, Hargeisa, Somaliland",
                            Code = "NEH-021",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "newhargeisa@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "New-Hargeisa",
                            Notes = "",
                            Phone = "+252 63 000021"
                        },
                        new
                        {
                            Id = 22,
                            Address = "SQA Branch, Hargeisa, Somaliland",
                            Code = "SQA-022",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "sqa@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "SQA",
                            Notes = "",
                            Phone = "+252 63 000022"
                        },
                        new
                        {
                            Id = 23,
                            Address = "Waheen Branch, Hargeisa, Somaliland",
                            Code = "WAH-023",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "waheen@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Waheen",
                            Notes = "",
                            Phone = "+252 63 000023"
                        },
                        new
                        {
                            Id = 24,
                            Address = "Wajaale Branch, Hargeisa, Somaliland",
                            Code = "WAJ-024",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "wajaale@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "Wajaale",
                            Notes = "",
                            Phone = "+252 63 000024"
                        },
                        new
                        {
                            Id = 25,
                            Address = "XWR Branch, Hargeisa, Somaliland",
                            Code = "XWR-025",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "xwr@company.com",
                            HiddenTasksJson = "[]",
                            IsActive = true,
                            Name = "XWR",
                            Notes = "",
                            Phone = "+252 63 000025"
                        });
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.BranchAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EndDate");

                    b.HasIndex("StartDate");

                    b.HasIndex("BranchId", "EndDate");

                    b.HasIndex("EmployeeId", "EndDate");

                    b.HasIndex("BranchId", "EmployeeId", "EndDate")
                        .HasFilter("\"EndDate\" IS NULL");

                    b.HasIndex("BranchId", "StartDate", "EndDate");

                    b.HasIndex("EmployeeId", "BranchId", "StartDate")
                        .IsUnique();

                    b.ToTable("BranchAssignments");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.DailyTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdjustmentMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("AdjustmentReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("BulkUpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsBulkUpdated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TaskDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("TaskDate");

                    b.HasIndex("TaskItemId");

                    b.HasIndex("BranchId", "IsCompleted");

                    b.HasIndex("BranchId", "TaskDate");

                    b.HasIndex("TaskDate", "IsCompleted");

                    b.HasIndex("BranchId", "TaskDate", "IsCompleted");

                    b.HasIndex("BranchId", "TaskItemId", "TaskDate")
                        .IsUnique();

                    b.HasIndex("TaskDate", "IsCompleted", "BranchId");

                    b.ToTable("DailyTasks");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "FIN",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Financial operations, cash management, and reconciliations",
                            IsActive = true,
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("ManagerId");

                    b.HasIndex("IsActive", "DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsWeekly")
                        .HasColumnType("boolean");

                    b.Property<int?>("WeekDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HolidayDate");

                    b.HasIndex("IsWeekly", "HolidayDate");

                    b.HasIndex("IsWeekly", "WeekDay");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Columns")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExportFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Filters")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IncludeCharts")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAscending")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("NextRunDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Recipients")
                        .HasColumnType("jsonb");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("RunCount")
                        .HasColumnType("integer");

                    b.Property<string>("ScheduleCron")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SortBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Configuration")
                        .HasDatabaseName("IX_Reports_Configuration_GIN");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Configuration"), "gin");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsPublic");

                    b.HasIndex("IsScheduled");

                    b.HasIndex("ReportType");

                    b.HasIndex("Tags")
                        .HasDatabaseName("IX_Reports_Tags_GIN");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("Category", "IsPublic");

                    b.HasIndex("IsScheduled", "NextRunDate");

                    b.HasIndex("ReportType", "IsActive");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.TaskAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DailyTaskId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DailyTaskId")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId", "AssignedAt");

                    b.HasIndex("EmployeeId", "DailyTaskId")
                        .IsUnique();

                    b.ToTable("TaskAssignments");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AvailableFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AvailableTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<TimeSpan>("Deadline")
                        .HasColumnType("interval");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutionType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSameDay")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxOccurrences")
                        .HasColumnType("integer");

                    b.Property<string>("MonthlyPattern")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeeklyDays")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("ExecutionType");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("IsActive", "ExecutionType");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new TimeSpan(0, 21, 0, 0, 0),
                            Description = "Complete daily coversheet and verify all entries",
                            DisplayOrder = 1,
                            ExecutionType = 0,
                            IsActive = true,
                            IsSameDay = true,
                            Name = "Coversheet"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new TimeSpan(0, 10, 0, 0, 0),
                            Description = "Scan and upload daily documents to system",
                            DisplayOrder = 2,
                            ExecutionType = 0,
                            IsActive = true,
                            IsSameDay = false,
                            Name = "Daily Scan"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new TimeSpan(0, 10, 0, 0, 0),
                            Description = "Scan meter readings and record in system",
                            DisplayOrder = 3,
                            ExecutionType = 0,
                            IsActive = true,
                            IsSameDay = false,
                            Name = "Meter Scan"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new TimeSpan(0, 21, 30, 0, 0),
                            Description = "Deposit meter collections to bank",
                            DisplayOrder = 4,
                            ExecutionType = 0,
                            IsActive = true,
                            IsSameDay = true,
                            Name = "Meter Deposit"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new TimeSpan(0, 8, 0, 0, 0),
                            Description = "Make daily bank deposit and update records",
                            DisplayOrder = 5,
                            ExecutionType = 0,
                            IsActive = true,
                            IsSameDay = false,
                            Name = "Daily Deposit"
                        });
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.Branch", b =>
                {
                    b.HasOne("TaskTracker.Models.Entities.Department", "Department")
                        .WithMany("Branches")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.BranchAssignment", b =>
                {
                    b.HasOne("TaskTracker.Models.Entities.Branch", "Branch")
                        .WithMany("BranchAssignments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTracker.Models.Entities.Employee", "Employee")
                        .WithMany("BranchAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.DailyTask", b =>
                {
                    b.HasOne("TaskTracker.Models.Entities.Branch", "Branch")
                        .WithMany("DailyTasks")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTracker.Models.Entities.TaskItem", "TaskItem")
                        .WithMany("DailyTasks")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.Employee", b =>
                {
                    b.HasOne("TaskTracker.Models.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaskTracker.Models.Entities.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.TaskAssignment", b =>
                {
                    b.HasOne("TaskTracker.Models.Entities.DailyTask", "DailyTask")
                        .WithOne("TaskAssignment")
                        .HasForeignKey("TaskTracker.Models.Entities.TaskAssignment", "DailyTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTracker.Models.Entities.Employee", "Employee")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyTask");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.Branch", b =>
                {
                    b.Navigation("BranchAssignments");

                    b.Navigation("DailyTasks");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.DailyTask", b =>
                {
                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.Department", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.Employee", b =>
                {
                    b.Navigation("BranchAssignments");

                    b.Navigation("Subordinates");

                    b.Navigation("TaskAssignments");
                });

            modelBuilder.Entity("TaskTracker.Models.Entities.TaskItem", b =>
                {
                    b.Navigation("DailyTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
